# -*- coding: utf-8 -*-
"""
/***************************************************************************
 cia
                                 A QGIS plugin
 build isochrones or isodistances maps from the "geoservice" API (french geographic institute)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-09-06
        copyright            : (C) 2022 by Lucas Fages
        email                : lucas.fages@laposte.net
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load cia class from file cia.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cia_geo import cia
    return cia(iface)
